### ISSUE TITLE
What are the plans for this fork?

### ISSUE THREAD

**Issue by lawrencegripper** [pulumi/terraform-provider-azurerm#5]
Hey, 

I was just looking at this issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1342 and noticed it's been worked on in this fork. 

I've been playing around a bit with Pulumi and was working on the assumption that the AzureRM provider was auto-gen'd from the release versions of the TF repo. 

Is the plan for the TF to diverge from the official repo in this fork or are changes made here going to be contributed back to the TF provider?

One concern is that the TF provider is pretty well policed with tests being added and integration tests being run - in the PR adding RBAC for AKS and Virtual Endpoints for Cosmos no tests have been added and their isn't an obvious integration build run.

**Comment by joeduffy** [comment]
We don't plan to maintain a permanent fork. All changes are meant to be upstreamed, but I'll admit we're unfortunately a bit behind on actually doing that.

@lukehoban We should definitely put together a plan here, maybe starting with a PR every other week?  Perhaps starting with the issue @lawrencegripper links to above. I'm actually not even sure how many diverged changes we have at this point (not just this repo, other providers too), but hopefully this will make a dent and gives us more understanding of how easy/hard it will be.

**Comment by lawrencegripper** [comment]
Cool, sounds like a good plan - thanks for the info!
